server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/powerup_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  admin:
    username: admin
    password: admin123
jwt:
  secret: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p
  expiration:
    millis: 3600000 # 1 Hora

logging:
  level:
    org.springframework.security: DEBUG